GET http://localhost:4004/odata/v4/employee/Employees HTTP/1.1

### GET Records with custom URL
GET http://localhost:4004/manageemployee/Employees HTTP/1.1

### POST call
POST http://localhost:4004/manageemployee/Employees  HTTP/1.1
Content-Type: application/json

{
      "employId": 106,
      "firstName": "Rahul",
      "lastName": "Sharma",
      "fullName": "Rahul Sharma",
      "email": "rahul.sharma@gmail.com",
      "phone": "3242344444",
      "designation": "Team Lead",
      "salary": "9534000.00",
      "managerName": "Vijay Darda",
      "baseLocation": "Pune",
      "proejctName": "BP",
      "joiningDate": "2026-04-25",
      "empAddress" :{
        "street" : "Yashone Street",
        "city": "Pune",
        "postalCode" : "234423",
        "country" : "India"
      }
    }


### Delete Operation

DELETE http://localhost:4004/manageemployee/Employees(102)

### UPDATE Operation only chage value updated and rest of fields willl be null
PUT http://localhost:4004/manageemployee/Employees(106) HTTP/1.1
Content-Type: application/json

{
      "ID": 106,
      "firstName": "Shubham",
      "lastName": "Verma",
      "fullName": "Shubham Verma",
      "email": "rahul.sharma@gmail.com",
      "phone": "3242344444",
      "designation": "Team Lead",
      "salary": "9534000.00",
      "managerName": "Vijay Darda",
      "baseLocation": "Pune",
      "proejctName": "BP",
      "joiningDate": "2026-04-25"
    }



### It will update requested fileds and rest of the things will be as it is
PATCH http://localhost:4004/manageemployee/Employees(106) HTTP/1.1
Content-Type: application/json

    {
      
      "joiningDate": "2027-04-25"
    }



### to Access underlying object

GET http://localhost:4004/manageemployee/Employees(ID=35201fab-428c-4b49-ac94-0997a0aa297f,employId=106)?$expand=empAddress

